### ISSUE TITLE
Bolts conflict with Expo/React-native

### ISSUE THREAD

**Issue by Uniphix** [iyegoroff/react-native-image-filter-kit#12]
React Native with Expo/ExpoKit
Expo: 32.0.0
ExpoKit: 32.0.7
React Native: SDK 32 / 0.59.1
React-Native Image Filter Kit: 0.3.4

Duplicate symbols because of Bolts already publically installed, it will work if I remove all references of Bolts, but I have to do this every time I do pod install.

duplicate symbol _warnBlockingOperationOnMainThread in:
    /Users/benwillard/Library/Developer/Xcode/DerivedData/socialdrip-bumkwadcqonpraczbjjnmkqdxctn/Build/Products/Debug-iphoneos/Bolts/libBolts.a(BFTask.o)
    /Users/benwillard/Library/Developer/Xcode/DerivedData/socialdrip-bumkwadcqonpraczbjjnmkqdxctn/Build/Products/Debug-iphoneos/RNImageFilterKit/libRNImageFilterKit.a(IFKTask.o)
ld: 1 duplicate symbol for architecture arm64

**Comment by iyegoroff** [comment]
@Uniphix , try to rename all conflicting identifiers inside rnifk Bolts dependency and submit a PR to this repo. Something like "adding 'ifk_' prefix" would be ok.

**Comment by Uniphix** [comment]
@iyegoroff can you clarify what exactly you mean?  I haven't done something like that before

**Comment by iyegoroff** [comment]
You need to rename (at least) this - https://github.com/iyegoroff/react-native-image-filter-kit/blob/7062d954d2a8e02fe41034392d53b88df68f7601/ios/Bolts/IFKTask.m#L19
