### ISSUE TITLE
How to send file path in  grayscale extraction without using Image tag

### ISSUE THREAD

**Issue by viraj-glide** [iyegoroff/react-native-image-filter-kit#122]
`<Grayscale
  style={styles.image}
  onFilteringError={
    ({ nativeEvent }) => dispatch(['show-error', new Error(nativeEvent.message)])
  }
  onExtractImage={({ nativeEvent }) => dispatch(['save-photo', nativeEvent.uri])}
  extractImageEnabled={true}
  image={
    <Image
      style={styles.image}
      source={{ uri: state[1] }}
    />
  }
/>`

Currently I am using above code for extraction but i don't want to use image tag I just want to extract grayscale image from my given uri direct to grayscale component and extract image path

**Comment by iyegoroff** [comment]
This is not supported, you have to use Image component to extract the file.
