### ISSUE TITLE
Does this library supports react-native-fast-image and other views for src and dst?

### ISSUE THREAD

**Issue by Navipro70** [iyegoroff/react-native-image-filter-kit#125]
Hello, first off, thanks for great library!

I'm using MultiplyBlend component with FastImage as src and View as dst for applying blending (makes images background similar to my view), but it does nothing, otherwise when I add to src and dst standard Image component from react-native, one with background and other is just image - all works fine. Can props dst and src support other Images/View excluding react-native and react-native-image-filter-kit components?

**Comment by iyegoroff** [comment]
Hi. No, only standard Image and ImageBackground components.

**Comment by NiccoloCase** [comment]
no hope for future support? it's a big miss
