### ISSUE TITLE
Filter without rendering

### ISSUE THREAD

**Issue by miladrasooli** [iyegoroff/react-native-image-filter-kit#13]
Hi ,
Is there anyway to render an image without rendering the output? I think it's a good feature to export filter APIs

**Comment by iyegoroff** [comment]
Hi @miladrasooli , something like this is not in the focus right now, but in the future I'll add an ability to save the result of filtering as temporary file.

**Comment by miladrasooli** [comment]
Thanks for your quick reply, any timeline ?

**Comment by iyegoroff** [comment]
Maybe in a couple of months.

**Comment by Bartson** [comment]
Any steps forward? Simple yes or no is enough, I just want to know if I should wait a little more.

**Comment by iyegoroff** [comment]
No news here. Consider provided options from my comments here - https://github.com/iyegoroff/react-native-color-matrix-image-filters/issues/12

**Comment by iyegoroff** [comment]
Also if you are interested in contributing to this library you can try to implement file system image caching in addition to existent in-memory caching and return the path to cached image in `onFilteringFinish` callback. It should be easier to start this feature on Android, because Fresco (which rnifk relies on) already has some file system caching support - https://frescolib.org/docs/caching.html

**Comment by iyegoroff** [comment]
Filtered image extraction is implemented in v0.7.0

**Comment by HarshitMadhav** [comment]
@iyegoroff Can you share some example code for the same or some URL of code?

**Comment by HarshitMadhav** [comment]
@iyegoroff Hi! Can you share some example code for the same or some URL of code for image extraction of filtered image?

**Comment by yairopro** [comment]
Hi @iyegoroff 

The issue is closed, but I don't see from the doc a way to apply a filter on an image without rendering it + `onExtractImage` prop.

Is there a function to apply a filter on an image without using a component ?

**Comment by iyegoroff** [comment]
Probably the closest thing to get "filtering without using a component" is rendering filter component outside of the viewport.
