### ISSUE TITLE
Cssgram filter blank

### ISSUE THREAD

**Issue by cernadasjuan** [iyegoroff/react-native-image-filter-kit#14]
Hi,

Im trying to apply the Xpro2 instagram filter, but i m getting a blank image, Am i doing something wrong? Thanks

```javascript
import { Xpro2 } from 'react-native-image-filter-kit'
import { Image } from 'react-native';

<Xpro2 image={<Image
              style={styles.publicationImage}
              source={{ uri: data.content }} />}></Xpro2>

```

**Comment by iyegoroff** [comment]
Hi @cernadasjuan , please specify your mobile platform(s) and react-native & react-native-image-filter-kit versions.

**Comment by cernadasjuan** [comment]
Mobile platform: Android 6 marshmallow (API level 23)
react native version: 0.57.3
react-native-image-filter-kit: 0.2.6 (with the last version, it throws an error at line 83 in MainReactPackageWithFrescoCache.java

**Comment by iyegoroff** [comment]
Try to use v0.3.5. Also if it is possible, please check if your problem replicates on iOS device.

**Comment by gyildirimm** [comment]
<Xpro2 image={<Image
              style={styles.publicationImage}
              source={{ uri: data.content }} />}></Xpro2>

How to change data.content filter  and save cameraRoll?
