### ISSUE TITLE
are there known issues with xcode emulators?

### ISSUE THREAD

**Issue by tsgouros** [iyegoroff/react-native-image-filter-kit#147]
Trying to develop an app with react-native 0.70.15, react-native-image-filter-kit 0.8.0, xcode emulator on iPhone 13/iOS 15 and iPhone 15/iOS 17. (Those are just the combinations I had at hand, not necessarily targets.)

I only get a black screen when I use react-native-image-filter-kit elements. Without it, images display fine. With any image-filter-kit element, no errors are shown (or not anywhere I know to look) but no images display, either.

Not sure where to go with this, but thought I'd at least ask if anyone was aware of emulator issues. Any other advice welcome, too. Thank you.

**Comment by ricardopetrere** [comment]
I'm facing a very similar issue! My specs are:

- macOS: Sonoma 14.4.1
- React-native: 0.70.15
- react-native-image-filter-kit: 0.8.0
- Xcode: 15.3
- Simulator: iPhone 15 Pro (iOS 17.4)

If I use an iOS 16.4 simulator (e.g. an iPhone 8 Plus), it works fine.

What was your solution, @tsgouros ? Or did you simply dropped it?

**Comment by tsgouros** [comment]
I'm afraid I don't remember exactly what fixed it, but in the end the immediate problem had more to do with me than the code, though it had been complicated by my attempt to import the image data into JS. My suspicion that there was some issue with the emulator was not justified. It works now, and there's a working example of using a react-native-image-filter-kit filter and using onExtractImage (and RNFetchBlob and @vivaxy/png) to get the result as a JS array at:  https://github.com/tsgouros/stellasonos-v4/blob/main/pages/ImagePage.js. Good luck!
