### ISSUE TITLE
App crashes on every device, but works on emulator

### ISSUE THREAD

**Issue by 13erikadelao** [iyegoroff/react-native-image-filter-kit#18]
I am using this library on my app, and it works totally fine on any android emulator, with any android sdk version over 17 ,but on a real device, it just crashes, it doesnt show an error, it just closes... and i have tested it, and it is not because i am calling a component the wrong way, it crashes with just simply installing it on my react native project. I tested the app on many android devices. And yes i am doing all the instructions specified. And yes, i already test the app without this library, and works totally fine. THE ONLY different thing that i did was that i put the new ImageFilterKitPackage() on my mainapplication.java rather than mainactivity.java

**Comment by DYuusha** [comment]
i have the same problem, the thing is, that i don't know how to get the crashes error, because i can't initialize the debug in my phone, i am using android.

**Comment by csto** [comment]
Same problem here.  I created a new react native app and ran `npm i react-native-image-filter-kit` then `react-native link react-native-image-filter-kit`.  I then set the minSdkVersion to 17.  The new app will crash on opening.  If I unlink this package, the app no longer crashes.  Any ideas?

**Comment by iyegoroff** [comment]
Please specify your react-native, react-native-image-filter-kit and gradle versions and provide a crashlog or reproducible example.

**Comment by csto** [comment]
You can view my test app at: https://github.com/csto/ImageKitDemo

react-native@0.59.9
react-native-image-filter-kit@0.3.8
gradle version is 3.4.0

I also tried older versions of all 3 without any luck.

It have confirmed that this runs fine on a Samsung Galaxy S5 (Android 6.0.1), but crashes on startup on a Samsung Galaxy S8 (Android 9) or Google Pixel XL (Android 8.1.0).

It crashes 100% of the time before startup on the Pixel XL and S8, so there are no logs from Metro or running react-native log-android.

Running `adb libcat *:E` against the Pixel XL I got:

```
06-14 10:36:59.405  1830  1833 E ANDR-PERF-OPTSHANDLER: Warning: Resource [2, 0] not supported for core 1. Instead use resource for core 0
06-14 10:36:59.405  1830  1833 E ANDR-PERF-RESOURCEQS: Failed to apply optimization [2, 2, 0]
06-14 10:36:59.450   882  2124 E ActivityManager: applyOptionsLocked: Unknown animationType=0
06-14 10:36:59.833 22968 22989 E SoLoader: Error when loading lib: dlopen failed: "/data/data/com.imagekitdemo/lib-main/libc++_shared.so" is 64-bit instead of 32-bit lib hash: 7ccd91485c9bd99f2c675e417db127e3 search path is /data/app/com.imagekitdemo-ESpuf5I_qrZ3FWtJV_Xjig==/lib/arm
06-14 10:36:59.834 22968 22989 E SoLoader: couldn't find DSO to load: libc++_shared.so caused by: dlopen failed: "/data/data/com.imagekitdemo/lib-main/libc++_shared.so" is 64-bit instead of 32-bit
06-14 10:36:59.834 22968 22989 E SoLoader: couldn't find DSO to load: libfb.so caused by: couldn't find DSO to load: libc++_shared.so caused by: dlopen failed: "/data/data/com.imagekitdemo/lib-main/libc++_shared.so" is 64-bit instead of 32-bit
06-14 10:36:59.834 22968 22989 E SoLoader: couldn't find DSO to load: libreactnativejni.so caused by: couldn't find DSO to load: libfb.so caused by: couldn't find DSO to load: libc++_shared.so caused by: dlopen failed: "/data/data/com.imagekitdemo/lib-main/libc++_shared.so" is 64-bit instead of 32-bit
06-14 10:36:59.836 22968 22989 E AndroidRuntime: FATAL EXCEPTION: create_react_context
06-14 10:36:59.836 22968 22989 E AndroidRuntime: Process: com.imagekitdemo, PID: 22968
06-14 10:36:59.836 22968 22989 E AndroidRuntime: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libreactnativejni.so caused by: couldn't find DSO to load: libfb.so caused by: couldn't find DSO to load: libc++_shared.so caused by: dlopen failed: "/data/data/com.imagekitdemo/lib-main/libc++_shared.so" is 64-bit instead of 32-bit
06-14 10:36:59.836 22968 22989 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
06-14 10:36:59.836 22968 22989 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
06-14 10:36:59.836 22968 22989 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
06-14 10:36:59.836 22968 22989 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
06-14 10:36:59.836 22968 22989 E AndroidRuntime: 	at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:31)
06-14 10:36:59.836 22968 22989 E AndroidRuntime: 	at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:19)
06-14 10:36:59.836 22968 22989 E AndroidRuntime: 	at com.facebook.react.jscexecutor.JSCExecutorFactory.create(JSCExecutorFactory.java:25)
06-14 10:36:59.836 22968 22989 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:944)
06-14 10:36:59.836 22968 22989 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
```

**Comment by csto** [comment]
Also, I updated Android Studio to the newest version the day before this crash started.

**Comment by iyegoroff** [comment]
@csto, I can't reproduce this crash, probably it is somehow related only to 64-bit devices. Maybe you can find some workarounds here - https://github.com/facebook/react-native/issues/2814

**Comment by iyegoroff** [comment]
fixed

**Comment by ghost** [comment]
I have same issue [here](https://stackoverflow.com/questions/74990078/react-native-app-crashing-in-other-devices-again-and-again-but-its-working-fine)

how I can solu this
