### ISSUE TITLE
"IFKImageFilter" was not found in the UIManager, with manual install.

### ISSUE THREAD

**Issue by alpsavrum** [iyegoroff/react-native-image-filter-kit#22]
I'm using react-native-navigation in my project and it uses some custom code for importing packages.

```
protected List<ReactPackage> getPackages() {
        // Add additional packages you require here
        // No need to add RnnPackage and MainReactPackage
        return Arrays.<ReactPackage>asList(
            // eg. new VectorIconsPackage()
        );
    }
```

Due to lack of manual import knowledge, I'm getting "IFKImageFilter" was not found in the UIManager error.

**Comment by iyegoroff** [comment]
Please specify your RN and RNIFK versions

**Comment by Tejaswini-PD** [comment]
@savrum @iyegoroff Any fixes for this ? Getting the error - `IFKImageFilterKit was not found in UIManager` on iOS. The error seems to be in image-filter.js file. Working fine on Android.

RN version: 0.63.3
RNIFK version: tried with both 0.6.0 and the latest version 0.7.3
