### ISSUE TITLE
Could not find com.github.iyegoroff:ReflectUtils:1.0.0

### ISSUE THREAD

**Issue by little-snow-fox** [iyegoroff/react-native-image-filter-kit#23]
Sorry, I can't run it successfully, my react-native versions: 0.60.5

Could not find com.github.iyegoroff:ReflectUtils:1.0.0.
Searched in the following locations:
  - file:/Users/snowfox/.m2/repository/com/github/iyegoroff/ReflectUtils/1.0.0/ReflectUtils-1.0.0.pom
  - file:/Users/snowfox/.m2/repository/com/github/iyegoroff/ReflectUtils/1.0.0/ReflectUtils-1.0.0.jar
  - file:/Users/snowfox/Developer/bigbug/BigbugMemberRnapp/node_modules/react-native/android/com/github/iyegoroff/ReflectUtils/1.0.0/ReflectUtils-1.0.0.pom
  - file:/Users/snowfox/Developer/bigbug/BigbugMemberRnapp/node_modules/react-native/android/com/github/iyegoroff/ReflectUtils/1.0.0/ReflectUtils-1.0.0.jar
  - file:/Users/snowfox/Developer/bigbug/BigbugMemberRnapp/node_modules/jsc-android/dist/com/github/iyegoroff/ReflectUtils/1.0.0/ReflectUtils-1.0.0.pom
  - file:/Users/snowfox/Developer/bigbug/BigbugMemberRnapp/node_modules/jsc-android/dist/com/github/iyegoroff/ReflectUtils/1.0.0/ReflectUtils-1.0.0.jar
  - file:/Users/snowfox/Developer/bigbug/BigbugMemberRnapp/android/app/https：/jitpack.io/com/github/iyegoroff/ReflectUtils/1.0.0/ReflectUtils-1.0.0.pom
  - file:/Users/snowfox/Developer/bigbug/BigbugMemberRnapp/android/app/https：/jitpack.io/com/github/iyegoroff/ReflectUtils/1.0.0/ReflectUtils-1.0.0.jar
  - https://dl.google.com/dl/android/maven2/com/github/iyegoroff/ReflectUtils/1.0.0/ReflectUtils-1.0.0.pom
  - https://dl.google.com/dl/android/maven2/com/github/iyegoroff/ReflectUtils/1.0.0/ReflectUtils-1.0.0.jar
  - https://jcenter.bintray.com/com/github/iyegoroff/ReflectUtils/1.0.0/ReflectUtils-1.0.0.pom
  - https://jcenter.bintray.com/com/github/iyegoroff/ReflectUtils/1.0.0/ReflectUtils-1.0.0.jar
Required by:
    project :app > project :react-native-image-filter-kit

**Comment by iyegoroff** [comment]
You have to add jitpack - https://github.com/iyegoroff/react-native-image-filter-kit#installation

**Comment by little-snow-fox** [comment]
It's my fault, thanks~
