### ISSUE TITLE
react-native-image-filter-kit:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by givik** [iyegoroff/react-native-image-filter-kit#26]
"react-native": "0.61.2",
"react-native-image-filter-kit": "^0.5.18",

```
Task :react-native-image-filter-kit:compileDebugJavaWithJavac FAILED
.../node_modules/react-native-image-filter-kit/android/src/main/java/iyegoroff/imagefilterkit/MainReactPackageWithFrescoCache.java:61: error: method does not override or implement a method from a supertype
  @Override
  ^
.../node_modules/react-native-image-filter-kit/android/src/main/java/iyegoroff/imagefilterkit/MainReactPackageWithFrescoCache.java:63: error: cannot find symbol
    List<ModuleSpec> modules = super.getNativeModules(context);
                                    ^
  symbol: method getNativeModules(ReactApplicationContext)
2 errors
```

same as https://github.com/iyegoroff/react-native-image-filter-kit/issues/15#issue-429326596

**Comment by iyegoroff** [comment]
Fixed in v0.6.0

**Comment by amritanshm21** [comment]
getting same error
only on android
Task :react-native-image-filter-kit:compileDebugJavaWithJavac FAILED

**Comment by kaleemlab** [comment]
> getting same error only on android Task :react-native-image-filter-kit:compileDebugJavaWithJavac FAILED

Try to set in (rn-image-filter-kit build gradle) :

from:    implementation "androidx.core:core-ktx:+"

to:     implementation "androidx.core:core-ktx:1.7.0"
