### ISSUE TITLE
After updating to mac os Catalina

### ISSUE THREAD

**Issue by givik** [iyegoroff/react-native-image-filter-kit#27]
gradle build --warning-mode=all --stacktrace

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-image-filter-kit:compileDebugRenderscript'.
> A problem occurred starting process 'command '.../Library/Android/sdk/build-tools/29.0.2/i686-linux-android-ld''
```
"react": "16.9.0",
"react-native": "0.61.2",
"react-native-image-filter-kit": "v0.6.0"

**Comment by iyegoroff** [comment]
Looks like a configuration problem. Please ensure that you followed installation guide for react-native ">=0.61.0"  - https://github.com/iyegoroff/react-native-image-filter-kit#installation

**Comment by phunguyenmurcul** [comment]
I've just installed react-native-image-filter-kit and followed installation guide for react-native >= 0.61.0 but still got this issue. 
@iyegoroff do you have any suggestions?

**Comment by givik** [comment]
@phunguyenmurcul I have downgraded to Mac OSX Mojave. Because of this, I could not build an app. I think it's more related to Android SDK rather than react-native-image-filter-kit. https://support.apple.com/en-us/HT208436#contactdeveloper.

See this:

Apple's transition to 64-bit technology is now complete. Starting with macOS Catalina, 32-bit apps are no longer compatible with macOS. If you have a 32-bit app, please check with the app developer for a 64-bit version.

<img width="1438" alt="Screen Shot 2019-10-28 at 11 54 44 PM" src="https://user-images.githubusercontent.com/2458760/67712947-5c69bc00-f9de-11e9-8f6e-9ab3d400b813.png">

**Comment by trankhacvy** [comment]
@givik Do you have any solution for this problem, I got same issue. Can't run debug android.

**Comment by givik** [comment]
The solution is to delete react-native-image-filter-kit from the project. Our talented team fixed it so Go ahead 🔨💯

**Comment by maxoux** [comment]
Same problem here, unable to compile for Android, anyone found a solution ?

**Comment by Muzzamil75** [comment]
Having the same problem please help me out !

**Comment by ManigandanRaamanathan** [comment]
@iyegoroff any fix for this? It works fine on mac OS but not building on windows

**Comment by iyegoroff** [comment]
@ManigandanRaamanathan no, I have never tried to build it on Windows.

**Comment by ManigandanRaamanathan** [comment]
@iyegoroff can you give it a try on windows?

**Comment by iyegoroff** [comment]
I don't use Windows in general. If you manage to build rnifk on Windows, please feel free to share your workaround here - #31 or open a pull request.

**Comment by ManigandanRaamanathan** [comment]
@iyegoroff may I know why this issue has been marked as closed?

**Comment by ManigandanRaamanathan** [comment]
@iyegoroff this is the error we are receiving 
![image](https://user-images.githubusercontent.com/22089729/81647350-77be8500-945f-11ea-8f6e-aca7b2e2b262.png)

**Comment by iyegoroff** [comment]
>may I know why this issue has been marked as closed?

Because it doesn't seem like an important issue - e.g. any other platform can be used to build rnifk

**Comment by DioSerdar** [comment]
So it's impossible to work with on windows? if so you should note this on read.me.

**Comment by kieran-Collins** [comment]
npx react-native run-android

**Comment by kieran-Collins** [comment]
when i run this npx react-native run-android
I got this
 **Task :react-native-image-filter-kit:compileDebugRenderscript FAILED**

i have followed all instruction of installation as per this link
https://github.com/iyegoroff/react-native-image-filter-kit

Configuration
OS
Ubuntu 18.04.5 LTS- 64bit
yarn -> 1.22.5
node-> v14.16.0
npm ->6.14.11

Tried on Android Studio's Virtual Device Pixel 4 XL API 29 Android 10 &&
On my device Samsung Galaxy S7

both did't run

**Comment by kieran-Collins** [comment]
when i run this npx react-native run-android
I got this
Task :react-native-image-filter-kit:compileDebugRenderscript FAILED

i have followed all instruction of installation as per this link
https://github.com/iyegoroff/react-native-image-filter-kit

Configuration
OS
Ubuntu 18.04.5 LTS- 64bit
yarn -> 1.22.5
node-> v14.16.0
npm ->6.14.11

Tried on Android Studio's Virtual Device Pixel 4 XL API 29 Android 10 &&
On my device Samsung Galaxy S7

both did't run

Tried installing package again in my Project
Tried this Solution with https://github.com/iyegoroff/react-native-image-filter-kit/issues/31
by changing android/app/build.gradle && android/build.gradle && gradle.wrapper.properties

I am New to React-Native and Android Apps.
Any Hints or Help will be really Gratefull for me.

**Comment by bekatd** [comment]
Anyone got this solved?

In my case, I am able to build the project locally BUT with a `buildToolsVersion` `29.0.2` instead of `29.0.3` as is stated in instruction.

    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 24
        compileSdkVersion = 29
        targetSdkVersion = 29
        renderscriptVersion = 21
        reactNativeFFmpegPackage = "min"
    }

But AppCenter build fails for android with the exact same log as OP stated :|

Now I am trying to build with `29.0.3` on AppCenter and let you know if it helps there

**Comment by trungnguyencmu** [comment]
// build.gradle
```buildToolsVersion = "29.0.3"
        minSdkVersion = 22
        compileSdkVersion = 29
        targetSdkVersion = 29
        supportLibVersion = "28.0.0"
        googlePlayServicesAuthVersion = "16.0.1"
        androidXAnnotation = "1.1.0"
        androidXBrowser = "1.0.0"
        renderscriptVersion = 21```

//gradle-wrapper.properties
distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-bin.zip

=> It worked for me
