### ISSUE TITLE
Dependency on Bolts giving error for UIWebView when submitting to App Store

### ISSUE THREAD

**Issue by bradyim** [iyegoroff/react-native-image-filter-kit#28]
I used react-native-image-filter-kit 0.6.1 and react-native 0.61.2. 

Dependency on Bolts 1.9 is giving an error for UIWebView when submitting to App Store. 

https://github.com/BoltsFramework/Bolts-ObjC/issues/331

**Comment by iyegoroff** [comment]
Fixed in v0.7.0
