### ISSUE TITLE
Windows: Task :react-native-image-filter-kit:compileDebugRenderscript FAILED

### ISSUE THREAD

**Issue by oleksyremigiusz1** [iyegoroff/react-native-image-filter-kit#31]
The error occurs even on fresh project with only react-native-image-filter-kit imported while trying to build an app using npx react-native .

>  What went wrong:
> Execution failed for task ':react-native-image-filter-kit:compileDebugRenderscript'.

Uninstalling package makes project work again.

I'm assuming that using Windows may be the problem.

I am using 
RN 0.61.5
react-native-image-filter-kit 0.7.0
Windows 7

**Comment by Bartson** [comment]
Same problem on Mac. 
OS: Catalina
RN 0.61.5

**Comment by iyegoroff** [comment]
@oleksyremigiusz1, I have never built it on Windows, so I don't know how this can be fixed. If you succeed in compiling rnifk on Windows, please feel free to share your workaround here or open a pull request with required fix.

@Bartson, other users report (#27) that rnifk can't be compiled on Catalina.

**Comment by Eugnis** [comment]
Same on Catalina. Only while compile Android

**Comment by Yigityakut** [comment]
I am having the same issue. Did you solve the problem?

**Comment by MR-Neto** [comment]
I was having the same issue and I found the following links. Now it's working for me.

On Catalina, build tools need to be updated to version 29.0.3 (https://developer.android.com/studio/releases/build-tools).

Plus, you must update your gradle plugin version to 3.6.0-rc02 or 4.0.0-beta1. (https://issuetracker.google.com/issues/142590626)

**Comment by juanjsebgarcia** [comment]
Where can one find the `4.0.0-beta1`? I only managed to find `com.android.tools.build:gradle:4.0.0-alpha09` on `mavenCentral`

**Comment by MR-Neto** [comment]
I couldn't find it too. Used 3.6.0-rc02

A sexta, 21/02/2020, 06:29, Juan <notifications@github.com> escreveu:

**Comment by ManigandanRaamanathan** [comment]
@MR-Neto @juanjsebgarcia @Yigityakut @Eugnis @oleksyremigiusz1 did you find any fix for this issue?

**Comment by Yigityakut** [comment]
@ManigandanRaamanathan  I decided to use other library to work with filters. gl-react-native-filters

**Comment by juanjsebgarcia** [comment]
@ManigandanRaamanathan I stashed my changes, and next time I went to try them it worked.

Apologies the following is in screenshots, this is the stash (fortunately had not deleted it!)

![Screenshot 2020-05-12 at 21 57 20](https://user-images.githubusercontent.com/16254139/81744910-c25df280-949b-11ea-9d9d-1ec27b73fbd5.png)
![Screenshot 2020-05-12 at 21 57 30](https://user-images.githubusercontent.com/16254139/81744915-c38f1f80-949b-11ea-97f5-8e0cccabce24.png)
![Screenshot 2020-05-12 at 21 57 44](https://user-images.githubusercontent.com/16254139/81744919-c5f17980-949b-11ea-9dee-cb01abbb33f7.png)
![Screenshot 2020-05-12 at 21 57 50](https://user-images.githubusercontent.com/16254139/81744923-c722a680-949b-11ea-9703-c2fd7ea2c786.png)
![Screenshot 2020-05-12 at 21 58 01](https://user-images.githubusercontent.com/16254139/81744929-c8ec6a00-949b-11ea-9e4e-6859c9bed98d.png)

**Comment by ManigandanRaamanathan** [comment]
@juanjsebgarcia thanks for the update. @iyegoroff we have fixed the issue by installing NDK version 20.0.559 from android studio. This required only on windows OS.

**Comment by babyrusa** [comment]
I had the same issue on Windows and fixed with having        ` buildToolsVersion = "29.0.2"` instead of     `buildToolsVersion = "29.0.3"`

**Comment by kieran-Collins** [comment]
when i run this npx react-native run-android
I got this
**Task :react-native-image-filter-kit:compileDebugRenderscript FAILED**

i have followed all instruction of installation as per this link
https://github.com/iyegoroff/react-native-image-filter-kit

**Configuration
OS
Ubuntu 18.04.5 LTS- 64bit
yarn -> 1.22.5
node-> v14.16.0
npm ->6.14.11**

**Ready to Provide more configuration if needed**

Tried on Android Studio's Virtual Device Pixel 4 XL API 29 Android 10 &&
On my device Samsung Galaxy S7

both did't run

Tried installing package again in my Project
Tried this Solution with https://github.com/iyegoroff/react-native-image-filter-kit/issues/31
by changing **android/app/build.gradle** && **android/build.gradle** && **gradle.wrapper.properties**

I am New to React-Native and Android Apps.
Any Hints or Help will be really Gratefull for me.

**Comment by SatalBill** [comment]
Same issue with this package. Still no solution yet?

**Comment by anastasia-son** [comment]
Same issue on macOS Ventura 
**Task :react-native-image-filter-kit:compileDebugRenderscript FAILED**

```
        buildToolsVersion = "33"
        minSdkVersion = 24
        compileSdkVersion = 33
        targetSdkVersion = 33
        kotlin_version = '1.6.20'
        ndkVersion = "21.4.7075529"
        supportLibVersion = "30.0.0"
```

**Comment by hashhirr** [comment]
on ios it is compiling like a charm i am only getting this error when i compile it on android.

**Comment by NiccoloCase** [comment]
have anyone found a solution?
