### ISSUE TITLE
Figma 'Layer blur' effect

### ISSUE THREAD

**Issue by teo029** [iyegoroff/react-native-image-filter-kit#36]
"react-native": "^0.62.0"
"react-native-image-filter-kit": "^0.7.1"

First of all, thank you for this great package. It really levels up your app's UI.

--- 

Q: How can I achieve blurring the bottom margin of this view? (or any other way to remove that visual delimiter)

![Simulator Screen Shot - iPhone SE 13 2 - 2020-04-10 at 14 26 10](https://user-images.githubusercontent.com/7328298/78987647-463c5c00-7b37-11ea-8e3d-51e93ffcf07c.png)

I want it to look more like this:

![Simulator Screen Shot - iPhone 11 Pro Max 13 2 - 2020-04-10 at 14 26 11](https://user-images.githubusercontent.com/7328298/78987658-4fc5c400-7b37-11ea-9bf4-59c1692196c4.png)

**Comment by iyegoroff** [comment]
@teo029, thanks for the feedback!

How does the original image look?

**Comment by teo029** [comment]
I have two versions:

![gradient2](https://user-images.githubusercontent.com/7328298/78991490-b819a300-7b41-11ea-8544-b8bc6ca663bf.png)

And exported with blur (but with that ugly delimiter):

![gradient](https://user-images.githubusercontent.com/7328298/78991520-c962af80-7b41-11ea-9760-82e783887ed0.png)

I usually work with SVG, but couldn't replicate the blur effect with any SVG library so I had to import the image as is.

**Comment by iyegoroff** [comment]
Maybe increasing the size of white-colored area for second image will reduce the difference between image bottom and background?

**Comment by teo029** [comment]
Trying different methods to do that. I will keep you updated.

**Comment by teo029** [comment]
Solve it with some Drop Shadow from Figma. Thank you!

**Comment by teo029** [comment]
Do you know any way to use insert views over the generated image? I am trying with `'position: absolute'` on the `MultiplyBlend` and with dstImage being an`<ImageBackground>` that contains my views, but nothing appears in both cases.
