### ISSUE TITLE
Is target API 29 on Android possible

### ISSUE THREAD

**Issue by todorone** [iyegoroff/react-native-image-filter-kit#37]
Hey @iyegoroff , thanks a lot for such an amazing library!

Is it possible to compile on Android targeting API 28 on Android? Currently API 29 is not officially supported by latest RN version and there are some deprecations on API 29 that makes some current libraries(like CameraRoll) do not work.

**Comment by iyegoroff** [comment]
Hi @todorone! Thanks for your feedback.

API 29 is required to prevent a renderscript-related crash on devices running 64-bit version of Android -> https://github.com/iyegoroff/react-native-image-filter-kit/issues/18#issuecomment-502135042
