### ISSUE TITLE
TypeError: null is not an object(evaluating 'IFKExtractedImagesCache.clen')

### ISSUE THREAD

**Issue by JonnaLennartsson** [iyegoroff/react-native-image-filter-kit#38]
Hi!
I'm trying to use rnifk in my app, but everytime I try to import the library I get this error:

TypeError: null is not an object(evaluating 'IFKExtractedImagesCache.clen')

I have tried to use rnifk 0.7.1 for both android and ios on:
Windows 10
with: 
"react-native": "~0.61.5"

And 

macOS Catalina 10.15.4
with: 
"react-native": "~0.61.5"

but I always get the same error.

![94258919_626805477898972_4062201131076419584_n](https://user-images.githubusercontent.com/43805911/80316709-a271d200-87ff-11ea-9890-7a1284575e5e.jpg)

Do you have any idea on how to fix this?
grateful for your help!

**Comment by iyegoroff** [comment]
Hi, @JonnaLennartsson!
This error means that library was not installed properly. 
If you are using expo, it will not work at all - just like any other module with native code - https://docs.expo.io/guides/using-clojurescript/#how-do-i-add-custom-native-modules

**Comment by JonnaLennartsson** [comment]
HI again!
I feel so stupid now...

But thank you! it works now, like a charm.

Thanks for the quick reply!
