### ISSUE TITLE
Android APK size increase x3

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [iyegoroff/react-native-image-filter-kit#39]
on building release android apk, the file size become 181 MB from initial 71MB. Any fix on this @iyegoroff

**Comment by ManigandanRaamanathan** [comment]
@iyegoroff at the moment I just wanted to use the instagram css filters and the feature to extract & store the filtered file on the device storage. In the readMe you've mentioned to use lightweight predecessor of this module react-native-color-matrix-image-filters. But the problem is that the predecessor does not provide the image extraction feature. And this library increased the file size 3 times larger than its initial release APK size.

**Comment by iyegoroff** [comment]
> the file size become 181 MB from initial 71MB

I'm not sure if this relates to rnifk. For example, CustomNativeFilter example app has 24 Mb sized apk.

**Comment by ThangNguyen1998** [comment]
i have same issue
