### ISSUE TITLE
How can I add to an image the instagram effects, CSSGram filters? 

### ISSUE THREAD

**Issue by luigbren** [iyegoroff/react-native-image-filter-kit#45]
How can I add to an image the instagram effects, **CSSGram filters**? and then save the changes and upload the file with the effects applied... some Tutorial?

Aden / AdenCompat
Brannan / BrannanCompat
Brooklyn / BrooklynCompat
Clarendon / ClarendonCompat
Earlybird / EarlybirdCompat
Gingham / GinghamCompat
..... more

**Comment by iyegoroff** [comment]
https://github.com/iyegoroff/react-native-image-filter-kit/blob/master/docs/image_extraction.md
