### ISSUE TITLE
excessive size in the generated png image onExtractImage

### ISSUE THREAD

**Issue by luigbren** [iyegoroff/react-native-image-filter-kit#47]
I'm making tests with the images that are in my gallery, captured with the camera (1080x1920), when applying the cssgram filters and extract the file to upload to the server (onExtractImage), the component changes me the format from jpg to png and the size is increased considerably, the original image is jpg and I have a size of 370KB, excellent! (resolution 1080x1920) after the extraction the new format is png with a resolution of 1080x1920 but with a size of 3.35MB, a very excessive size 370KB -> 3.35MB
```

<FiltroComponent                            
   onExtractImage={({ nativeEvent }) => {
      Image.getSize(nativeEvent.uri, (width, height) => {
         datosimage = []
         let arrayfil = { uri: nativeEvent.uri, width: width, height: height, mime: "image/png" };
         datosimage.push(arrayfil)
      });
  }}
/>
```

**Comment by iyegoroff** [comment]
Duplicate #46
