### ISSUE TITLE
Build Failed: Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by Garamani** [iyegoroff/react-native-image-filter-kit#48]
###  The app crashes due to react-native-image-filter-kit, this is the crash log:
**Xcode build failed > Error:**
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RCTImageView", referenced from:
      objc-class-ref in IFKImageFilter.o
      __OBJC_$_CATEGORY_RCTImageView_$_CacheKey in RCTImageView+CacheKey.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
**Terminal Error:**
```
The following build commands failed:
        .../Library/Developer/Xcode/DerivedData/MY_PROJECT-dxmgqdxborzhroajvyivtvivrlsi/Build/Products/Debug-iphonesimulator/react-native-image-filter-kit/react_native_image_filter_kit.framework/react_native_image_filter_kit normal x86_64
(1 failure)
```
_**react_native_image_filter_kit was installed properly based on documentation via: pod install**_

**what I've done to fix the issue with no success:**
- Upgrading macOs from **Mojave** to **Catalina**
- Upgrading Xcode from 10.2 to 11.4
- Adding javaScriptCore.framework > Build Phases > Link Binary and Libraries (for both my_project & my_projectTests)

**Current System Info:**
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 234.01 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.15.1 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.4/11N132i - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.9.0 => 16.9.0 
    react-native: ^0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by Garamani** [comment]
**To the maintainer:**
This is the best and the only solution we have in react native community to filter images. (There is also gl-react but the react native branch seems to be deprecated)
So,
Would you please give me some clues to find the source of problem?

**Comment by iyegoroff** [comment]
Please check if you are able to build any [example](https://github.com/iyegoroff/react-native-image-filter-kit/tree/master/examples)

**Comment by Garamani** [comment]
I used this example from README:
```
import {
  SoftLightBlend,
  Emboss,
  Earlybird,
  Invert,
  RadialGradient
} from 'react-native-image-filter-kit';

const result = (
  <Earlybird
    image={
      <SoftLightBlend
        resizeCanvasTo={'dstImage'}
        dstTransform={{
          scale: 'CONTAIN'
        }}
        dstImage={
          <Emboss
            image={
              <Image
                style={{ width: 320, height: 320 }}
                source={require('./parrot.png')}
                resizeMode={'contain'}
              />
            }
          />
        }
        srcTransform={{
          anchor: { x: 0.5, y: 1 },
          translate: { x: 0.5, y: 1 }
        }}
        srcImage={
          <Invert
            image={
              <RadialGradient
                colors={['rgba(0, 0, 255, 1)', '#00ff00', 'red']}
                stops={[0.25, 0.75, 1]}
                center={{ x: '50w', y: '100h' }}
              />
            }
          />
        }
      />
    }
  />
)
```
As soon as I enable the import of 'react-native-image-filter-kit', the build is failed. I simplified the example by only applying the SoftLightBlend and the build failed again. 
before rebuilding the app this is the error message appeared:
![Simulator Screen Shot - iPhone 11 - 2020-07-03 at 08 12 00](https://user-images.githubusercontent.com/47912427/86430649-16e95580-bd08-11ea-811b-df1ade80f42f.png)

**Comment by Garamani** [comment]
I just checked and the build will fail unless you uninstall the react-native-image-filter-kit.

**Comment by iyegoroff** [comment]
That error means that native part of the module can't be accessed - e.g. it was not installed properly.

**Comment by abdelhedydev** [comment]
In node_modules/react-native-filter-image-kit/react-native-image-filter-kit.podspec
add this ligne :
**s.static_framework = true**
you entire file will be : 
`require 'json'

package = JSON.parse(File.read(File.join(__dir__, 'package.json')))

Pod::Spec.new do |s|
  s.name             = package['name']
  s.version          = package['version']
  s.summary          = package['description']
  s.homepage         = package['homepage']
  s.license          = package['license']
  s.author           = package['author']
  s.platform         = :ios, '9.0'
  s.source           = { :git => 'https://github.com/iyegoroff/react-native-image-filter-kit.git', :tag => 'v#{s.version}' }
  s.source_files     = 'ios/**/*.{h,m}'
  s.resource_bundles = { 'bundle' => ['ios/Resources/*.cikernel'] }
  s.requires_arc     = true

  s.dependency 'React'
  s.static_framework = true
  s.dependency 'Bolts/Tasks', '1.9.0'
end
`

thx to [https://github.com/bbeldame](https://github.com/bbeldame)

**Comment by abdelhedydev** [comment]
Add this line in your react-native-image-filter-kit.podspec , this file exist in node_modules / react-native-image-filter-kit
**s.static_framework = true**
your entire file should be : 

```
require 'json'

package = JSON.parse(File.read(File.join(__dir__, 'package.json')))

Pod::Spec.new do |s|
  s.name             = package['name']
  s.version          = package['version']
  s.summary          = package['description']
  s.homepage         = package['homepage']
  s.license          = package['license']
  s.author           = package['author']
  s.platform         = :ios, '9.0'
  s.source           = { :git => 'https://github.com/iyegoroff/react-native-image-filter-kit.git', :tag => 'v#{s.version}' }
  s.source_files     = 'ios/**/*.{h,m}'
  s.resource_bundles = { 'bundle' => ['ios/Resources/*.cikernel'] }
  s.requires_arc     = true

  s.dependency 'React'
  s.static_framework = true
  s.dependency 'Bolts/Tasks', '1.9.0'
end
```

Thx to [https://github.com/bbeldame](https://github.com/bbeldame)
