### ISSUE TITLE
How to trigger onExtractImage ?

### ISSUE THREAD

**Issue by adityajhordanbapr** [iyegoroff/react-native-image-filter-kit#50]
Hi All, I just confused how to trigger onExtractImage, I already set extractImageEnabled to true.
In the documentation, onExtractImage will trigger every time the filtering result changes, but the question is how to change the result ? 

I already tried to create a function to update the image, but onExtractImage still not triggered. I using version 0.7.1

Please help, thank you

**Comment by adityajhordanbapr** [comment]
@iyegoroff

**Comment by adityajhordanbapr** [comment]
Also, I trying this one 


`            <ImageFilter
              extractImageEnabled={true}
              onFilteringStart={({ nativeEvent }) =>
                console.log("on filter start : ", nativeEvent)
              }
              onFilteringFinish={({ nativeEvent }) =>
                console.log("on filter finish : ", nativeEvent)
              }
              onFilteringError={({ nativeEvent }) =>
                console.log("on filter error : ", nativeEvent)
              }
              onExtractImage={({ nativeEvent }) =>
                console.log("on filter succes : ", nativeEvent)
              }
              config={{
                name: this.state.filterModel,
                image: {
                  name: "SoftLightBlend",
                  resizeCanvasTo: "dstImage",
                  dstTransform: {
                    scale: "CONTAIN",
                  },
                  dstImage: {
                    name: this.state.filterModel,
                    image: (
                      <Image
                        style={{ width: 320, height: 320 }}
                        source={Family}
                        resizeMode={"contain"}
                      />
                    ),
                  },
                  srcTransform: {
                    anchor: { x: 0.5, y: 1 },
                    translate: { x: 0.5, y: 1 },
                  },
                  srcImage: {
                    name: "Invert",
                    image: {
                      name: "RadialGradient",
                      colors: ["rgba(0, 0, 255, 1)", "#00ff00", "red"],
                      stops: [0.25, 0.75, 1],
                      center: { x: "50w", y: "100h" },
                    },
                  },
                },
              }}
            />`

and create function to update filter dynamic, but onExtractImage never triggered

**Comment by iyegoroff** [comment]
Please create a minimal repro.
