### ISSUE TITLE
Images get blurry on iPhones but the same code performs well on Android.

### ISSUE THREAD

**Issue by Tharuka-Nimesha** [iyegoroff/react-native-image-filter-kit#51]
mobile platform(s) - iOS
react-native Version - 0.62.2
react-native-image-filter-kit - 0.7.3

<Grayscale
style={{height:'100%', width:'100%'}}
onFilteringError={
      ({ nativeEvent }) => {console.log(nativeEvent)}
}
onExtractImage={({ nativeEvent }) => {setUrl(nativeEvent.uri);}}
extractImageEnabled={true}
image={
< Image
source={{uri:route.params.newImage.path}}
resizeMode="cover"
style={styles.photo}
/>
}
/>

Feedback is much appreciated. Thanks in advance.

**Comment by iyegoroff** [comment]
This doesn't seem related to rnifk. Image can be blurry because of some simulator/devserver issues.

**Comment by necixy** [comment]
Make sure you're not using "debug" mode as with me it was the cause of blurry images.

**Comment by RaphaelHadjadj** [comment]
I have the same issue even with a production build on iOS.
How could we solve it ? Do you have any ideas ?

**Comment by cmora** [comment]
@iyegoroff I have the same issue. Looks like the issue is related to the `resizeMode="cover"`. The issue its only happening on IOS and when you add the resizeMode to cover. Any ideas about this?

**Comment by cmora** [comment]
@RaphaelHadjadj @Tharuka-Nimesha I just realized that the issue is related to the cache and the resizeMode="cover". I just disabled the cache for the thumbnails images and looks like this is working now for the main image.

```<SelectedFilterComponent
          onFilteringStart={onFilteringStart}
          onFilteringFinish={onFilteringFinish}
          onExtractImage={onExtractImage}
          extractImageEnabled={false}
          disableCache={disableCache}
          style={[StyleSheet.absoluteFillObject]}
          image={children}
        />```
