### ISSUE TITLE
App crashes when filtering started and app get to background

### ISSUE THREAD

**Issue by li4e** [iyegoroff/react-native-image-filter-kit#56]
Platform: iOS
"react-native": "0.62.2"
"react-native-image-filter-kit": "^0.7.2"

**App crashes with**
`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'`

**Problem in file**
`/ios/IFKImageFilter.m`
line 171

**How to reproduce:**
When filtering is started and not completed yet, press home button to get app to background, and app crashes

p.s.
I have not enough experience with Objective C to resolve this issue. May be anybody could help with this. Thank you.

**Comment by iyegoroff** [comment]
Please create reproducible example.
