### ISSUE TITLE
Blank screen at the place of image in production .it is working in development only. 

### ISSUE THREAD

**Issue by ambessh** [iyegoroff/react-native-image-filter-kit#57]
- Please specify your mobile platform(s) and react-native & react-native-image-filter-kit versions. Also check https://github.com/iyegoroff/react-native-image-filter-kit#status if your react-native-image-filter-kit version corresponds with your react-native version and ensure that you followed this installation guide - https://github.com/iyegoroff/react-native-image-filter-kit#installation

- Sometimes cleaning the project could resolve build issues: press `Shift + Cmd + K` in Xcode and run `cd android && ./gradlew clean` in terminal

- In case you use Expo you have to switch to 'bare workflow' in order to use this module

- If your app crashed due to react-native-image-filter-kit, please attach a crash log or provide a minimal repro

**Comment by iyegoroff** [comment]
You need to answer the questions from issue template.

**Comment by dhirajanand014** [comment]
This issue is not resolved with version 0.8.0 This is an open issue. For me the build works fine. But the FIlters wont get loaded at all.
