### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by microinginer** [iyegoroff/react-native-image-filter-kit#58]
* What went wrong:
Execution failed for task ':react-native-image-filter-kit:compileDebugRenderscript'.
> com.android.ide.common.process.ProcessException: Error while executing process /home/inginer/Android/Sdk/build-tools/29.0.3/llvm-rs-cc with arguments {-I /home/inginer/Android/Sdk/build-tools/29.0.3/renderscript/include/ -I /home/inginer/Android/Sdk/build-tools/29.0.3/renderscript/clang-include/ -I /home/inginer/apps/ArtPicFilter/node_modules/react-native-image-filter-kit/android/src/main/rs/blend -I /home/inginer/apps/ArtPicFilter/node_modules/react-native-image-filter-kit/android/src/main/rs/gradients -rs-package-name=androidx.renderscript -p /home/inginer/apps/ArtPicFilter/node_modules/react-native-image-filter-kit/android/build/generated/renderscript_source_output_dir/debug/out -target-api 21 /home/inginer/apps/ArtPicFilter/node_modules/react-native-image-filter-kit/android/src/main/rs/blend/MultiplyBlend.rs /home/inginer/apps/ArtPicFilter/node_modules/react-native-image-filter-kit/android/src/main/rs/blend/DifferenceBlend.rs /home/inginer/apps/ArtPicFilter/node_modules/react-native-image-filter-kit/android/src/main/rs/blend/HueBlend.rs /home/inginer/apps/ArtPicFilter/node_modules/react-native-image-filter-kit/android/src/main/rs/blend/ColorDodgeBlend.rs /home/inginer/apps/ArtPicFilter/node_modules/react-native-image-filter-kit/android/src/main/rs/blend/ColorBurnBlend.rs /home/inginer/apps/ArtPicFilter/node_modules/react-native-image-filter-kit/android/src/main/rs/blend/ExclusionBlend.rs /home/inginer/apps/ArtPicFilter/node_modules/react-native-image-filter-kit/android/src/main/rs/blend/SaturationBlend.rs /home/inginer/apps/ArtPicFilter/node_modules/react-native-image-filter-kit/android/src/main/rs/blend/HardLightBlend.rs /home/inginer/apps/ArtPicFilter/node_modules/react-native-image-filter-kit/android/src/main/rs/blend/ColorBlend.rs /home/inginer/apps/ArtPicFilter/node_modules/react-native-image-filter-kit/android/src/main/rs/blend/SoftLightBlend.rs /home/inginer/apps/ArtPicFilter/node_modules/react-native-image-filter-kit/android/src/main/rs/blend/LuminosityBlend.rs /home/inginer/apps/ArtPicFilter/node_modules/react-native-image-filter-kit/android/src/main/rs/gradients/SmoothLinearGradient.rs /home/inginer/apps/ArtPicFilter/node_modules/react-native-image-filter-kit/android/src/main/rs/gradients/SmoothRadialGradient.rs /home/inginer/apps/ArtPicFilter/node_modules/react-native-image-filter-kit/android/src/main/rs/gradients/EllipticalGradient.rs /home/inginer/apps/ArtPicFilter/node_modules/react-native-image-filter-kit/android/src/main/rs/gradients/SmoothSweepGradient.rs /home/inginer/apps/ArtPicFilter/node_modules/react-native-image-filter-kit/android/src/main/rs/gradients/RectangularGradient.rs /home/inginer/apps/ArtPicFilter/node_modules/react-native-image-filter-kit/android/src/main/rs/gradients/QuadGradient.rs /home/inginer/apps/ArtPicFilter/node_modules/react-native-image-filter-kit/android/src/main/rs/compositing/DestinationATopCompositing.rs /home/inginer/apps/ArtPicFilter/node_modules/react-native-image-filter-kit/android/src/main/rs/compositing/SourceOutCompositing.rs /home/inginer/apps/ArtPicFilter/node_modules/react-native-image-filter-kit/android/src/main/rs/compositing/SourceInCompositing.rs /home/inginer/apps/ArtPicFilter/node_modules/react-native-image-filter-kit/android/src/main/rs/compositing/DestinationInCompositing.rs -O 3 -o /home/inginer/apps/ArtPicFilter/node_modules/react-native-image-filter-kit/android/build/generated/res/rs/debug/raw}

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

**Comment by gstcarv** [comment]
did you manage to fix it?

**Comment by ricardopetrere** [comment]
Did you?
