### ISSUE TITLE
Error: Invariant failed: ImageFilterKit: 'Poprocket' filter doesn't exist on ios

### ISSUE THREAD

**Issue by trungphotobank** [iyegoroff/react-native-image-filter-kit#64]
I did that follow example, still filter good, but I got Error when reload app 
<img width="1079" alt="Screen Shot 2021-04-13 at 14 31 11" src="https://user-images.githubusercontent.com/54518789/114514119-26b5a300-9c65-11eb-96d6-6ae4340a12a5.png">

Please help me!

**Comment by iyegoroff** [comment]
Poprocket and Ashby filters are defined in CustomFilter example app, not in rnifk package itself.
