### ISSUE TITLE
Android build assembleRelease issue

### ISSUE THREAD

**Issue by dhirajanand014** [iyegoroff/react-native-image-filter-kit#72]
- Mobile platform Android platform 29 has issues in loading the filters when built for release. Check with the installation document and followed the same
- This happens for the following version - 
    - RN - 0.64.1
    - RN Image filter kit - 0.8.0
    - Android 29 - 
      - buildscript {
          ext {
              buildToolsVersion = "30"
              minSdkVersion = 21
              compileSdkVersion = 30
              targetSdkVersion = 30
           }
      }

- After './gradlew clean and './gradlew assembleRelease' executions, there is no error on build. The build is successful. However, the filter images don't get loaded at all. 
- There is no issue when running locally or ./gradlew assembleDebug.
- No Expo used
- No app crash and no error logs. Attached the screenshot and video recording

Issue after ./gradlew assembleRelease - 
https://user-images.githubusercontent.com/29733508/119179932-30fd6500-ba8d-11eb-87b0-90416f33a96e.mp4

No issues after ./gradlew assembleDebug

https://user-images.githubusercontent.com/29733508/119180405-e29c9600-ba8d-11eb-9d40-07a3e73046e8.mp4

Please assist in resolving. This is causing lots of issues.

**Comment by dhirajanand014** [comment]
Any updates on this issue?

**Comment by iyegoroff** [comment]
Clone this repo and check if your problem reproduces on [CustomNativeFilter](../tree/master/examples/CustomNativeFilter) example or provide your own minimal reproducible example.
