### ISSUE TITLE
could not write file ScriptC_ColorDodgeBlend.java

### ISSUE THREAD

**Issue by filex88** [iyegoroff/react-native-image-filter-kit#73]
Hi, I get this error when I try to build the project after installing the module. I have tried but there is no way to fix it. I use windows and RN 64.0.

**> Task :react-native-image-filter-kit:compileDebugRenderscript FAILED**

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
143 actionable tasks: 8 executed, 135 up-to-date
**Error: could not write file ScriptC_ColorDodgeBlend.java**   
Failed to generate class ScriptC_ColorDodgeBlend ()        
RSContext::reflectToJava : failed to do reflection ((null))

My configurations are:
        buildToolsVersion = "30.0.0"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        supportLibVersion   = "30.0.0"
        googlePlayServicesVersion   = "17.0.0"
        androidMapsUtilsVersion     = "0.5+"
        googlePlayServicesVisionVersion = "18.0.0"
        googlePlayServicesAuthVersion = "16.0.1"
        ndkVersion = "20.1.5948944"

Thank you very much.

**Comment by iyegoroff** [comment]
Hi @filex88. What is your react-native-image-filter-kit version?

**Comment by mohita-lgg** [comment]
Hi @iyegoroff , I am getting kind of same error in Android.
react-native-image-filter-kit version :-  0.8.0
react-native :- 0.63

`Error: could not write file ScriptC_ColorBlend.java
Failed to generate class ScriptC_ColorBlend ()
RSContext::reflectToJava : failed to do reflection ((null))


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-image-filter-kit:compileDebugRenderscript'.
> com.android.ide.common.process.ProcessException:`

**Comment by iyegoroff** [comment]
Hi @mohita-lgg, please check installation instructions - with rn 0.63 you have to use rnifk 0.7.3

**Comment by konstantinblaesi** [comment]
Hi, I try to build and run an app from a 3rd party and get very similar errors despite these versions. What could be the cause?
> ├─ react-native-image-filter-kit@0.8.0
> └─ react-native@0.69.6

errors
```
Error: Command failed: gradlew.bat app:installSomeAppDebug -PreactNativeDevServerPort=8081
Error: could not write file ScriptC_DestinationATopCompositing.java
Failed to generate class ScriptC_DestinationATopCompositing ()
RSContext::reflectToJava : failed to do reflection ((null))
```

removing this library from the dependencies and codebase fixes the build
