### ISSUE TITLE
This library only supports 32-bit (armeabi-v7a) on Android phones?

### ISSUE THREAD

**Issue by hannto-guodong** [iyegoroff/react-native-image-filter-kit#76]
I have followed all instruction of installation as per this link
https://github.com/iyegoroff/react-native-image-filter-kit

But I get errors in a 64-bit environment; is this library only supported in 32-bit?

Configuration:
OS: Window 10
react-native: 0.63.4
react-native-image-filter-kit: ^0.7.3

  ext {
        buildToolsVersion = "28.0.2"
        minSdkVersion = 17
        compileSdkVersion = 29
        targetSdkVersion = 29
        renderscriptVersion = 21
    }

**Comment by iyegoroff** [comment]
Yes, this library supports phones running 64-bit version of Android OS. What kind of error did you get?

**Comment by hannto-guodong** [comment]
Thank you for your reply，Errors are caused me and I have resolved;
I found the class "Renderscript" used in the code, which will be deprecated at API level 31 on Android OS, Will this library be updated for it?

**Comment by iyegoroff** [comment]
No plans to update it right now.
