### ISSUE TITLE
 ERROR    TypeError: null is not an object (evaluating 'IFKExtractedImagesCache.clean')

### ISSUE THREAD

**Issue by BazingaZeta** [iyegoroff/react-native-image-filter-kit#84]
I am using react native V0.63, I followed the installation steps provided for my version and tried to use an example found on StackOverflow:
```
import { Image } from 'react-native'
import {
  RadialGradient,
  ImageBackgroundPlaceholder
} from 'react-native-image-filter-kit'

const imageStyle = { width: 320, height: 320 }

const gradient = (
  <RadialGradient
    colors={['red', '#00ff00', 'blue']}
    stops={[0, 0.5, 1]}
    image={
      <ImageBackgroundPlaceholder style={imageStyle}>
        /* your content here */
      </ImageBackgroundPlaceholder>
    }
  />
)
```

The terminal is throwing this error:
`
[Wed Aug 18 2021 11:45:09.414]  ERROR    TypeError: null is not an object (evaluating 'IFKExtractedImagesCache.clean')
[Wed Aug 18 2021 11:45:09.415]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
[Wed Aug 18 2021 11:45:10.456]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)`

Using radial gradients on React Native seems very tricky! Any idea why this is happening?

**Comment by iyegoroff** [comment]
This error means that native part of the module can't be accessed, probably the module was not linked properly.

**Comment by Niltonsf** [comment]
Any fixes for this?
