### ISSUE TITLE
Not working some instagram filters in Android release build with enabled ProGuard

### ISSUE THREAD

**Issue by NikitaDudin** [iyegoroff/react-native-image-filter-kit#89]
### Environment
react-native-image-filter-kit: 0.8.0
Platform: Android
Project settings: 
```java       
        buildToolsVersion = "30.0.3"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        ndkVersion = "22.1.7171670"
```
OS: MacOS Big Sur 11.6 (20G165)
Node.js: 16.13.0
xCode: 13.1 (13A1030d)
android/app/build.gradle: 
```java
def enableProguardInReleaseBuilds = true
```
react-native: 0.64.3

### Solution
add to android/app/proguard-rules.pro file:
```pro
# react-native-image-filter-kit 
-keep class com.facebook.react.views.image.** { *; }
-keep class com.facebook.drawee.** { *; }
```

### Linked issue
- #72

**Comment by iyegoroff** [comment]
Thank you! Just updated the readme with your solution.
