### ISSUE TITLE
can disImage/srcImage accept <View> Component?

### ISSUE THREAD

**Issue by est7** [iyegoroff/react-native-image-filter-kit#9]
my code is 
```react
<XorComposition
        dstImage={
            <View style={ { backgroundColor:'black',width: 320, height: 320 }
            }>
              <Text>aaaa</Text>
            </View>
          }
          srcImage={
            <Image
              style={ { width: 320, height: 320 }
              }
              source={{ uri: 'http://www.myiconfinder.com/uploads/iconsets/256-256-53d5151ca4f467ed9951f85024881c85.png' }}
            />
          }
        />
```

but it doesnt work

i find dstImage's type is  Filterable<Rest>
` type Filterable<Rest> = React.ReactElement<unknown> | Config<Rest>`

how can I give <View> Component to disImage

**Comment by iyegoroff** [comment]
It will not work with `Text` - only `Image` and `ImageBackground` components can be filtered.
https://github.com/iyegoroff/react-native-image-filter-kit/blob/master/docs/types.md#filterable

You should pass [TextImage](https://github.com/iyegoroff/react-native-image-filter-kit/blob/master/docs/generators.md#TextImage) to `dstImage` prop.
