### ISSUE TITLE
Image dimensions sometimes wrong for filtered PNG

### ISSUE THREAD

**Issue by jzxchiang1** [iyegoroff/react-native-image-filter-kit#91]
Android 11 emulator
RN 0.64.2
filter-kit 0.8.0

I noticed the filtered image extracted to the filesystem has different dimensions than the original image when I call `Image.getSize` on it.

This happened on the Android emulator dummy camera image. The original photo was a 1080x1440 JPEG of size 22195 bytes. The filtered photo became a 945 x 1260 PNG of size 259661 bytes. I had to resize and compress it with `react-native-image-resizer` to get it back to the original dimensions as a JPEG with a reasonable file size.

Any help would be appreciated.

**Comment by iyegoroff** [comment]
Is it reproduced with [ImageExtraction](https://github.com/iyegoroff/react-native-image-filter-kit/tree/master/examples/ImageExtraction) example?
