### ISSUE TITLE
Error: cannot find symbol import com.facebook.react.views.image.ReactImageDownloadListener

### ISSUE THREAD

**Issue by muhammadashfaq** [iyegoroff/react-native-image-filter-kit#92]
System:
    OS: macOS 11.5.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 49.29 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.2 - /usr/local/opt/node@14/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/opt/node@14/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7583922
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: ~0.63.3 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
    
    
    Unable to build android with this library

Anyone has fixed this issue

**Comment by osamamukhtarvd** [comment]
Same issue happening to me. Any fix so far?

**Comment by iyegoroff** [comment]
Please specify your react-native & react-native-image-filter-kit versions.

**Comment by HiromuTsuchiya** [comment]
Same issue happening to me.

"react-native": "0.64.3",
  "react-native-image-filter-kit": "^0.7.3",

**Comment by iyegoroff** [comment]
@HiromuTsuchiya 
You have to use latest version of react-native-image-filter-kit (currently 0.8.0)

**Comment by virenradadiya** [comment]
any solution for that. The same issue also happening to me.
    "react-native": "0.63.4",
    "react-native-image-filter-kit": "^0.8.0",

**Comment by mikpalm** [comment]
Same issue with 0.8.0
